---
title: "&#39;Catch&#39; n&#227;o pode aparecer ap&#243;s &#39;Finally&#39; dentro de uma instru&#231;&#227;o &#39;Try&#39; | Microsoft Docs"
ms.custom: ""
ms.date: "11/16/2016"
ms.prod: "visual-studio-dev14"
ms.reviewer: ""
ms.suite: ""
ms.technology: 
  - "devlang-visual-basic"
ms.tgt_pltfrm: ""
ms.topic: "article"
f1_keywords: 
  - "vbc30379"
  - "bc30379"
helpviewer_keywords: 
  - "BC30379"
ms.assetid: 33d1278b-cf10-4c66-aaf8-08a4372f370b
caps.latest.revision: 8
caps.handback.revision: 8
author: "stevehoag"
ms.author: "shoag"
manager: "wpickett"
---
# &#39;Catch&#39; n&#227;o pode aparecer ap&#243;s &#39;Finally&#39; dentro de uma instru&#231;&#227;o &#39;Try&#39;
Um `Catch` instrução aparece no código após o `Finally` terminando um `Try` Bloco de instrução.`Catch` deve aparecer em um `Try...Catch...Finally` Bloco de instrução.  
  
 **ID do erro:** BC30379  
  
### Para corrigir este erro  
  
1.  Mova o `Catch` instrução para um local apropriado no código.  
  
## Consulte também  
 [Instrução Try...Catch...Finally](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)   
 [Tratamento de visão geral do Visual Basic de exceções estruturado](http://msdn.microsoft.com/pt-br/bb81af80-a735-4873-9711-6151a48e418a)