---
title: "Bloco &#39; catch&#39; nunca alcan&#231;ado porque &#39;&lt; Nome1 &gt;&#39; herda de &#39;&lt; nome2 &gt;&#39; | Microsoft Docs"
ms.custom: ""
ms.date: "11/16/2016"
ms.prod: "visual-studio-dev14"
ms.reviewer: ""
ms.suite: ""
ms.technology: 
  - "devlang-visual-basic"
ms.tgt_pltfrm: ""
ms.topic: "article"
f1_keywords: 
  - "BC42029"
  - "vbc42029"
helpviewer_keywords: 
  - "BC42029"
ms.assetid: 4bc84a84-ec7e-49db-8794-4fb71d36d5c0
caps.latest.revision: 12
caps.handback.revision: 12
author: "stevehoag"
ms.author: "shoag"
manager: "wpickett"
---
# Bloco &#39; catch&#39; nunca alcan&#231;ado porque &#39;&lt; Nome1 &gt;&#39; herda de &#39;&lt; nome2 &gt;&#39;
Um `Catch` bloco dentro do código nunca é alcançado.  
  
 Por padrão, essa mensagem é um aviso. Para obter mais informações sobre como ocultar avisos ou tratar avisos como erros, consulte [Configurando avisos no Visual Basic](/visual-studio/ide/configuring-warnings-in-visual-basic).  
  
 **ID do erro:** BC42029  
  
### Para corrigir este erro  
  
-   Remover o estranhas `Catch` bloco.  
  
## Consulte também  
 [Como: testar código com um bloco Try... Bloco Catch no Visual Basic](http://msdn.microsoft.com/pt-br/8368e205-ed73-4185-a247-af84fb4fafa9)   
 [Instrução Try...Catch...Finally](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)